In [1]:
import numpy as np # generic math functions
import matplotlib.pyplot as plt
#%matplotlib notebook
%matplotlib inline

In [3]:
from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d # Hilbert space spin basis
import numpy as np # generic math functions
import time

def Ham_nonint(L):
    basis = spin_basis_1d(L)
    hz=(np.sqrt(5)+1)/4 #parameters used by Kim and Huse
    hx=(np.sqrt(5)+5)/8
    J=1.0
    hz_arr = [[hz,i] for i in range(L)] 
    hx_arr = [[hx,i] for i in range(L)] 
    J_arr =[[J,i,(i+1)] for i in range(L-1)] # OBC  [[J,i,(i+1)%L] for i in range(L)] # PBC
    
    # static and dynamic lists
    static = [["zz",J_arr],["z",hz_arr], ["x",hx_arr] ]
    dynamic =[]
    H = hamiltonian(static,dynamic,basis=basis,dtype=np.float_,check_symm=False,check_herm=False)
    return H


def output_gauge_potent(Ham,L):
    E,V= Ham.eigh()
    op_lamb_arr = del_lambda_Ham(L).toarray()
    x=np.dot(op_lamb_arr, V)
    num_lamb_mat =np.dot(V.T,x) #matrix multiplication
    wij = np.outer(E,np.ones(2**L))-np.outer(np.ones(2**L),E)
    return wij, num_lamb_mat
  
def gauge_potent_mu(wij,num_lamb_mat,mu):
    A_lamb = -1j*np.multiply(wij,num_lamb_mat)/(wij**2+ mu**2)#element-wise multiplication
    return A_lamb


def del_lambda_Ham(L):
    basis = spin_basis_1d(L)  
    hx_lamb=1.0
    hx_lamb_arr = [[hx_lamb,i] for i in range(L)] 
    static_lamb = [["x",hx_lamb_arr]]
    dynamic_lamb =[]
    op_lamb=hamiltonian(static_lamb,dynamic_lamb,basis=basis,dtype=np.float_,check_symm=False,check_herm=False)
    return op_lamb

def norm(A_lamb):    
    return np.linalg.norm(A_lamb, 'fro')

In [10]:
L=2
ham= Ham_nonint(L)
E,V= ham.eigh()
wij, num_lamb_mat= output_gauge_potent(ham,L)

In [ ]:
def delta(omega, omega_ij, tol):
    index_lower = np.tril_indices(2**L,-1)
    wij_arr=wij[index_lower]
    wij_min_nonint[= min(wij_arr)
    wij_max_nonint[i]=max(wij_arr)
    output should be index of energy levels
    

In [13]:
L=2
print wij

[[ 0.         -1.30336868 -2.53739238 -5.37271366]
 [ 1.30336868  0.         -1.2340237  -4.06934498]
 [ 2.53739238  1.2340237   0.         -2.83532128]
 [ 5.37271366  4.06934498  2.83532128  0.        ]]


In [16]:
for i in range(   2**L):
    print wij[0,i]

0.0
-1.30336867773
-2.53739237785
-5.37271365535
